#!/bin/zsh

BRANCH="${1}"
if [ -z "${BRANCH}" ]; then
  BRANCH=$(git branch --show-current)

  if [ -z "${BRANCH}" ]; then
    echo "could not detect a branch"
    exit 1
  fi
  echo "📦 Detected branch: $BRANCH"
fi

git fetch origin "+refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH}"
